name: Create/upload auxiliary files to the release.

on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'dev'
    paths-ignore:
      - '*.txt'
      - '*.md'

jobs:
  upload_github_release:
    permissions:
      contents: write   # nécessaire pour gérer les tags et releases
      actions: read

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Supprimer et recréer le tag Nightly sur le dernier commit
      - name: Reset Nightly tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -d Nightly || true
          git push origin :refs/tags/Nightly || true
          git tag Nightly
          git push origin Nightly

      - name: Generate changelog
        run: git log --pretty=format:"%ad %an %s" --date=short > Git-Changelog.txt

      - name: Add auxiliary files to the release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Nightly
          tag_name: Nightly
          prerelease: true
          files: |
            Git-Changelog.txt
            ./SourceCode.zip
            ./SourceCode.tar.gz