name: Create/upload auxiliary files to the release.

on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'dev'
    paths-ignore:
      - '*.txt'
      - '*.md'

jobs:
  release_dev:
    if: github.ref_name == 'dev'
    permissions:
      contents: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Reset Dev tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -d Dev || true
          git push origin :refs/tags/Dev || true
          git tag Dev
          git push origin Dev

      - name: Generate changelog
        run: git log --pretty=format:"%ad %an %s" --date=short > Git-Changelog.txt

      - name: Create source archives
        run: |
          git archive --format=zip --output=SourceCode-dev.zip HEAD
          git archive --format=tar.gz --output=SourceCode-dev.tar.gz HEAD

      - name: Add files to Dev release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Dev Nightly
          tag_name: Dev
          prerelease: true
          files: |
            Git-Changelog.txt
            SourceCode-dev.zip
            SourceCode-dev.tar.gz

  release_main:
    if: contains(fromJson('["master","main"]'), github.ref_name)
    permissions:
      contents: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Reset Nightly tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -d Nightly || true
          git push origin :refs/tags/Nightly || true
          git tag Nightly
          git push origin Nightly

      - name: Generate changelog
        run: git log --pretty=format:"%ad %an %s" --date=short > Git-Changelog.txt

      - name: Create source archives
        run: |
          git archive --format=zip --output=SourceCode-nightly.zip HEAD
          git archive --format=tar.gz --output=SourceCode-nightly.tar.gz HEAD

      - name: Add files to Nightly release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Nightly
          tag_name: Nightly
          prerelease: true
          files: |
            Git-Changelog.txt
            SourceCode-nightly.zip
            SourceCode-nightly.tar.gz